### ISSUE TITLE
Data, files and mappings prepared to populate the new version

### ISSUE THREAD

**Issue by jairomelo** [ImaginingFutures/metadata-schema#24]
Prepare data now available in ifrepo.world for transfer in a fresh installation

- [x] [Archiving COVID-19 Heritage in Ho Chi Minh City](https://ifrepo.world/Detail/collections/7)
- [x] [Documenting Street Art in Ankara](https://ifrepo.world/Detail/collections/47)
- [x] [Food, Hospitality, and the Micro-cultures of Syria](https://ifrepo.world/Detail/collections/4)
- [x] [Vernacular Songs as Archives and Modes of Social Redress in Jamestown, Accra](https://ifrepo.world/Detail/collections/46)

**Comment by Zabandosk** [comment]
Data has been prepared. Last changes pushed to [main branch](https://github.com/ImaginingFutures/metadata-schema/tree/main)
